name: Github Devops CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Run the code
        run: npm run start

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            build/
            package*.json
  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./artifacts

      - name: Build Docker image
        run: |
          docker build -t zackzc/github-devops-app ./artifacts

      - name: Run Docker container
        run: |
          docker run --name nodejs-app zackzc/github-devops-app
